source 'https://rubygems.org'


gem 'rails', '4.2.4'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

gem 'faraday', '0.9.1'

gem 'haml-rails', '~> 0.9'

group :development, :test do
  gem 'byebug'
  gem 'pry-byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
end
