# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 551af2f317f8bf3e2b9d9f5aa745c5fcd6f0b17b68e47bb2f0d490065e47d42fa3ad0fda77d1ba25773cd477b2ee7a59a8672f905bad3ec400dd5dc417420fa8

test:
  secret_key_base: 31bf7d9162b82c733597b077c8e360991e4ea1b7b28abe097c35772832cf998b2c657a7a79f91f29304e221898a11eb86531863c490284ec3ff1a6d6351f303b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
