source 'https://rubygems.org'


gem 'rails', '4.2.4'

gem 'sqlite3'

gem 'jbuilder', '~> 2.0'

group :development, :test do
  gem 'byebug'
  gem 'pry-byebug'

  gem 'rspec-rails', '~> 3.0'
end

group :development do
  gem 'web-console', '~> 2.0'
end

group :test do
  gem 'rack-vcr'
end
